### ISSUE TITLE
CSS sytle for citation?

### ISSUE THREAD

**Issue by majdal** [mgmeyers/obsidian-pandoc-reference-list#94]
This is a feature request:

Currently, the rendered reference appears in the same style as the rest of the text. It would be nice to be able to style it somehow (e.g. give the entire text a different colour, or maybe just the year).

**Comment by nhan000** [comment]
@ankitp94 Do you mind sharing your CSS snippets? Thank you!

**Comment by ankitpensia** [comment]
I put the following in a .css file in the snippets folder. You might need to change the color based on your theme.  

```
.pandoc-citation {
    color: #BED754 !important;
    text-decoration: none !important;
    font-weight: none;
}
```

**Comment by ankitp94** [comment]
@nhan000 I put the following in a .css file in the snippets folder. You might need to change the color based on your theme.  

```
.pandoc-citation {
    color: #BED754 !important;
    text-decoration: none !important;
    font-weight: none;
}
```

**Comment by kall-tech** [comment]
I also wanted this feature and apparently the add-on allows for style customisation via the [style settings plugin](https://github.com/mgmeyers/obsidian-style-settings) (as mentioned in #12 and #21). However, for me, that did not seem to have any effect.

I wanted to style resolved/unresolved citations differently, so this CSS snippet is what I found to be working for my case:

```CSS
.pandoc-citation.is-resolved {
    /* same style as links */
    color: var(--link-color);
    text-decoration: var(--link-decoration);
}

.pandoc-citation:not(.is-resolved) {
    background-color: #ffbcbc;
    border-left: 3px solid #cc0000;
    padding-left: 5px;
}
```
